SocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("main.urls", "main"), namespace="main")),
    path('api/', include(("api.urls", "api"), namespace="api")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path

from .views import UserView, accountPage
from .views import HomeView, uploadPage
from .views import showProfilePics, showPostPics, deletePics
from .views import showfullpost
from .views import searchPage, searchUsers
from .views import CommentView, likePost
from .views import sendRequest, delRequest, requestPage, acceptRequest
from .views import showFriends, unfriendUsers, myFriendFeed
from .views import deletePost, myPosts
from .views import getNotifications, read_notification, readAllNots

urlpatterns = [
    path("feedPage/", HomeView.as_view(), name="homeView"),
    path('account/', accountPage, name="accountPage"),
    path('myAccount/', UserView.as_view(), name='userView'),
    path('uploads/', uploadPage, name="uploadPage"),
    path('proPics/', showProfilePics, name="profilePics"),
    path('postPics/', showPostPics, name="postPics"),
    path('deletePics/', deletePics, name="deletePics"),
    path('deletePost/', deletePost, name="deletePost"),
    path('fullPost/', showfullpost, name="fullPost"),
    path('myPosts/', myPosts, name="myPosts"),
    path("likePost/<int:requestType>/", likePost, name="likePost"),
    path('postComment/', CommentView.as_view(), name="postComment"),
    path('delComment/<int:cid>', CommentView.as_view(), name="delComment"),
    path('searchPage/', searchPage, name="searchPage"),
    path('searchUsers/', searchUsers, name="searchUsers"),
    path('sendRequest/<int:toUser>/', sendRequest, name="sendRequest"),
    path('delRequest/<int:byUser>/<int:toUser>/', delRequest, name="delRequest"),
    path('requestPage/', requestPage, name="requestPage"),
    path('acceptRequest/<int:by>/', acceptRequest, name="acceptRequest"),
    path('myFriends/', showFriends, name="showFriends"),
    path('unfriend/', unfriendUsers, name="unfriendUsers"),
    path('friendFeed/<int:friendID>', myFriendFeed, name="myFriendFeed"),
    path('getNots/', getNotifications, name="getNots"),
    path('readNotification/', read_notification, name="readNotification"),
    path('readAllNots/', readAllNots, name="readAllNots")
    
]

main/urls.py
from django.urls import path

from .views import sign_out, LoginUser, NewUser
from .views import homePage, accountPage, notificationPage, requestsPage, searchPage
from .views import changePassword

urlpatterns = [
    path('', LoginUser.as_view(), name="login"),
    path('create/', NewUser.as_view(), name="signup"),
    path('logout/', sign_out, name="logout"),
    path('home/', homePage, name="homePage"),
    path("account/", accountPage, name="accountPage"),
    path("notifications/", notificationPage, name="notifications"),
    path("requests/", requestsPage, name="requestsPage"),
    path("search/", searchPage, name="searchPage"),
    path("changePassword/", changePassword, name="changePassword")
]

templates/components/notifications.html
{% load customFilters %}
<div class="d-flex justify-content-center mt-2">

    <div class="card w-75">
        <h4 class="card-title ms-2 mt-2">Notifications
            <button class="float-end btn btn-sm btn-secondary me-2 mt-2" onclick="markAllRead()">Mark All as Read</button>
        </h4>
        <div class="card-body">
            <ul class="list-group">
                {%for notify in notifications%}
                <li class="list-item mt-2 ms-2">
                    {%createString "api/readNotification/?notId=" notify.id "&page=" notifications.number as nURL%}
                    {%if not notify.isread%}
                    <button class="btn btn-lg btn-outline-success btn-sm" onclick="readNotification('{{nURL}}')">{{notify.notification}}
                        &nbsp;&nbsp;<h6 class="float-end">{{notify.created}}</h6>
                    </button>
                    {%else%}
                    <button class="btn btn-lg btn-success btn-sm" onclick="readNotification('{{nURL}}')">{{notify.notification}}
                        &nbsp;&nbsp;<h6 class="float-end">{{notify.created}}</h6>
                    </button>
                    {%endif%}
                </li>
                {%endfor%}
            </ul>
        </div>
        <nav>
            <ul class="pagination justify-content-center">
                {%if notifications.has_previous%}
                <li class="page-item me-2">
                    {%createString "api/getNots/?page=" notifications.previous_page_number as pURL%}
                    <button class="page-link" onclick="goToPreviousPage('main-Space', '{{pURL}}')">Previous</button>
                </li>
                {%endif%}
                <li class="page-item fs-4">
                    <b>Page {{ notifications.number }} of {{ notifications.paginator.num_pages }}.&nbsp;</b>
                </li>
                {%if notifications.has_next%}
                <li class="page-item">
                    {%createString "api/getNots/?page=" notifications.next_page_number as nextURL%}
                    <button class="page-link" onclick="goToNextPage('main-Space', '{{nextURL}}')">Next</button>
                </li>
                {%endif%}
            </ul>
        </nav>
    </div>
</div>

templates/components/sideBar.html
<div class="d-flex">

    <div class="sidebar" id="mainSideBar">
        <div class="closeButton">
            <a href="javascript:void(0)" onclick="closeNav()">&#9747;</a>
        </div>
        <a href="javascript:void(0)" onclick="goHome()">Home</a>
        <a href="javascript:void(0)" onclick="goToAccount()">Account</a>
        <a class="position-relative" href="javascript:void(0)" onclick="getNotifications()">Notifications
            <span class="position-absolute top-2 start-90 translate-middle badge rounded-pill bg-transparent" 
            id="notify-count">
                {%if request.user.notify_count != 0%}
                {{request.user.notify_count}}
                {%else%}
                    0
                {%endif%}
                </span>
        </a>
        <a class="position-relative" href="javascript:void(0)" onclick="getRequests()">Requests
            <span class="position-absolute top-2 start-90 translate-middle badge rounded-pill bg-transparent" 
            id="requests-count">
                {%if request.user.request_count != 0%}
                {{request.user.request_count}}
                {%else%}
                    0
                {%endif%}
                </span>
        </a>
        <a href="javascript:void(0)" onclick="goToSearch()">Search</a>
        <div class="userOpts">
                <div class="userImage">
                    <img src="{{request.user.profile_pic.url}}">
                </div>
                <div class="dropDownMenu">
                    <div class="dropup dropup-center">
                        <button class="btn btn-outline-light dropdown-toggle btn-sm btnBr" type="button" data-bs-toggle="dropdown">
                          {{request.user.get_fullname}}
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href={% url 'main:changePassword' %}>Change Password</a></li>
                          <li><a class="dropdown-item" href="{% url "main:logout" %}">Logout</a></li>
                        </ul>
                      </div>
                </div>
        </div>
    </div>

    <div class="headerTitle" id="header">
        <a onclick="openNav()" href="javascript:void(0)" id="openNavBtn">&#9776;</a>
        <p>Social Media</p>
    </div>

    
</div>